<a href="https://colab.research.google.com/github/KinzaAslam/DSA_20SW071/blob/main/Task%2004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
X = np.arange(2, 34, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [2]:
import numpy as np

X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print(X)
print(Y)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [3]:
#Task3

import numpy as np
X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [9]:
from google.colab import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)


Drive already mounted at /NumPy.ipnyb; to attempt to forcibly remount, call drive.mount("/NumPy.ipnyb", force_remount=True).
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-1.64877706  0.46253582  1.24358206 ... -1.24157516  0.08921133
   0.9787313 ]
 [ 0.86460155 -1.5237962   0.60341628 ... -0.76828811  0.20283073
   1.0879192 ]
 [ 1.21941523  1.26132701  1.00892322 ... -0.1593808  -0.67702688
   1.2489368 ]
 ...
 [ 1.53350127  0.59921634 -0.37158433 ...  0.3422758  -1.72177119
  -1.04884652]
 [-1.28706039 -1.05949453 -1.24709508 ...  0.6889378   0.41205672
  -0.03643973]
 [ 0.03969426 -0.14668842  0.4161009  ... -1.2595656   1.55864281
   1.5578418 ]]
Average of all values in X_norm: 7.460698725481051e-18
Average of minimum values in each column of X_norm: -1.718286739846383
Average of maximum values in each column of X_norm: 1.722732598362126
Random permutation of row indices: [649 808 441 497 868 779 991 973 451 377 555 484 402 206 160 914 984 755